// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrciysahrywlckszpmls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyY2l5c2Focnl3bGNrc3pwbWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODUxOTQsImV4cCI6MjA2NTA2MTE5NH0.Q7bwpedcCmK7MAYX0Dkwo8itSq1rKAjB29FilbhPkTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);